name: CCTV
version: '${version}'
main: io.github.tanguygab.cctv.CCTV
api-version: 1.18
authors: [Streampy, Timdecoole123, Tanguygab]
description: A real CCTV plugin with working CCTV for a real usage.
softdepend: [ItemsAdder, PlaceholderAPI]
commands:
  CCTV:
    description: Main command